source 'https://rubygems.org'

gem 'middleman', '~> 4.2'
gem 'middleman-autoprefixer', '~> 2.7'
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]
gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw]
gem 'dotenv'
gem 'middleman-imageoptim', :git => 'https://github.com/plasticine/middleman-imageoptim', :branch => 'master'
gem 'pry'
